id:                             3
pretrained: Null
model:
    name:                       baseline_eff_net
    args:
        version:                2
        nclasses:               42
        freeze:                 False
optimizer:
    name:                       Adam
    args:
        lr:                     0.0001
loss:
    name:                       SmoothedCrossEntropy
    args:
metric:
    -   name:                   Accuracy
        args:                   Null
scheduler:
    name:                         ReduceLROnPlateau
    args:
        mode:                     min
        factor:                   0.5
        patience:                 5 
        verbose:                  True     
dataset:
    train:
        name: shopee_raw
        args:
            data_root_dir:      data/         
            train_dir:          train/train/
            test_dir:           test/test/
            csv_train_dir:      train.csv  
            csv_val_dir:        val.csv
            csv_test_dir:       test.csv
            is_train:           True  
        loader:
            name: shopee_loader
            args:
                batch_size:     32
                shuffle:        True
    val:
        name: shopee_raw
        args:
            data_root_dir:      data/          
            train_dir:          train/train/
            test_dir:           test/test/
            csv_train_dir:      train.csv  
            csv_val_dir:        val.csv
            csv_test_dir:       test.csv
            is_train:           False  
        loader:
            name: shopee_loader
            args:
                batch_size:     32
trainer: 
    nepochs: 15
    cp_dir: 'checkpoint/'
    val_step: 1
    log_step: 1
