id: 1
pretrained: Null
model:
    name:                       baseline_eff_net
    args:
        version:                2
        nclasses:               42
        freeze:                 False
optimizer:
    name:                       Adam
    args:
        lr:                     0.01
loss:
    name:                       SmoothedCrossEntropy
    args:
metric:
    -   name:                   Accuracy
        args:                   Null
    -   name:                   ConfusionMatrix
        args:                       
            nclasses:           42
            output_dir:         '/home/ken/shopee_ws/cp'    
scheduler:
    name:                       CosineAnnealingLR
    args:
        T_max:                  2306        
dataset:
    train:
        name: shopee_raw
        args:
            data_root_dir:      /home/ken/shopee_ws/data/         
            train_dir:          train/train/
            test_dir:           test/test/
            csv_train_dir:      train.csv  
            csv_val_dir:        val.csv  
            csv_test_dir:       test.csv
            is_train:           True  
        loader:
            name: shopee_loader
            args:
                batch_size:     2
                shuffle:        True
    val:
        name: shopee_raw
        args:
            data_root_dir:      /home/ken/shopee_ws/data/          
            train_dir:          train/train/
            test_dir:           test/test/
            csv_train_dir:      train.csv  
            csv_val_dir:        val.csv
            csv_test_dir:       test.csv
            is_train:           False  
        loader:
            name: shopee_loader
            args:
                batch_size:     2
trainer: 
    nepochs: 10
    cp_dir: /home/ken/shopee_ws/cp/
    val_step: 1
    log_step: 1
